<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGqgpxli\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGqgpxli/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGqgpxli.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGqgpxli\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerGqgpxli\appDevDebugProjectContainer([
    'container.build_hash' => 'Gqgpxli',
    'container.build_id' => '4ff6ec32',
    'container.build_time' => 1627127439,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGqgpxli');
